name: nlp
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - scikit-learn
    - pandas
    - gensim
    - nltk
    - spacy 
    - ipython
    - jupyter
    - ipdb
    - openpyxl
    - xlrd
    - pip
    pip:
        - pyldavis
